"""initial schema

Revision ID: ddc735870db4
Revises: 
Create Date: 2026-06-19 15:57:11.499467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddc735870db4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('nome', sa.String(length=256), nullable=False),
    sa.Column('iniciais', sa.String(length=8), nullable=True),
    sa.Column('segmento', sa.String(length=256), nullable=True),
    sa.Column('porte', sa.String(length=128), nullable=True),
    sa.Column('cidade', sa.String(length=128), nullable=True),
    sa.Column('uf', sa.String(length=4), nullable=True),
    sa.Column('site', sa.String(length=256), nullable=True),
    sa.Column('cnpj', sa.String(length=32), nullable=True),
    sa.Column('responsavel', sa.String(length=128), nullable=True),
    sa.Column('servico', sa.String(length=256), nullable=True),
    sa.Column('origem', sa.String(length=256), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('score_base', sa.Integer(), nullable=True),
    sa.Column('score_ajustado', sa.Boolean(), nullable=True),
    sa.Column('ia_score', sa.Boolean(), nullable=True),
    sa.Column('score_rationale', sa.Text(), nullable=True),
    sa.Column('resumo_sinal', sa.Text(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('novidade', sa.Text(), nullable=True),
    sa.Column('ultimo_rastreio', sa.String(length=32), nullable=True),
    sa.Column('contato', sa.JSON(), nullable=True),
    sa.Column('memoria', sa.JSON(), nullable=True),
    sa.Column('intencao', sa.JSON(), nullable=True),
    sa.Column('estrategia', sa.JSON(), nullable=True),
    sa.Column('proveniencia', sa.JSON(), nullable=True),
    sa.Column('validacao', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_nome'), ['nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresas_responsavel'), ['responsavel'], unique=False)
        batch_op.create_index(batch_op.f('ix_empresas_score'), ['score'], unique=False)

    op.create_table('sinais',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('empresa_id', sa.String(length=64), nullable=False),
    sa.Column('tipo', sa.String(length=128), nullable=True),
    sa.Column('titulo', sa.String(length=512), nullable=True),
    sa.Column('fonte', sa.String(length=128), nullable=True),
    sa.Column('data', sa.String(length=16), nullable=True),
    sa.Column('relevancia', sa.Integer(), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('ia', sa.Boolean(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('validado', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sinais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sinais_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('timeline_entries',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('empresa_id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.String(length=32), nullable=True),
    sa.Column('tipo', sa.String(length=64), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_entries_empresa_id'), ['empresa_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_entries_empresa_id'))

    op.drop_table('timeline_entries')
    with op.batch_alter_table('sinais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sinais_empresa_id'))

    op.drop_table('sinais')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_score'))
        batch_op.drop_index(batch_op.f('ix_empresas_responsavel'))
        batch_op.drop_index(batch_op.f('ix_empresas_nome'))

    op.drop_table('empresas')
    # ### end Alembic commands ###
